# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notif.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotif.proto\x12\x05notif\"!\n\x0cQuoteRequest\x12\x11\n\tnum_quote\x18\x01 \x01(\x05\"(\n\rQuoteResponse\x12\x17\n\x0fgenerated_quote\x18\x01 \x01(\t\"\"\n\rImagesRequest\x12\x11\n\tnum_image\x18\x01 \x01(\x05\".\n\x0eImagesResponse\x12\x1c\n\x14generated_image_urls\x18\x01 \x01(\t2\x88\x01\n\x0cNotifService\x12\x37\n\x08GetQuote\x12\x13.notif.QuoteRequest\x1a\x14.notif.QuoteResponse0\x01\x12?\n\x0eGenerateImages\x12\x14.notif.ImagesRequest\x1a\x15.notif.ImagesResponse0\x01\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notif_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_QUOTEREQUEST']._serialized_start=22
  _globals['_QUOTEREQUEST']._serialized_end=55
  _globals['_QUOTERESPONSE']._serialized_start=57
  _globals['_QUOTERESPONSE']._serialized_end=97
  _globals['_IMAGESREQUEST']._serialized_start=99
  _globals['_IMAGESREQUEST']._serialized_end=133
  _globals['_IMAGESRESPONSE']._serialized_start=135
  _globals['_IMAGESRESPONSE']._serialized_end=181
  _globals['_NOTIFSERVICE']._serialized_start=184
  _globals['_NOTIFSERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
