# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notif_pb2 as notif__pb2


class NotifServiceStub(object):
    """Define the Notification service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuote = channel.unary_stream(
                '/notif.NotifService/GetQuote',
                request_serializer=notif__pb2.QuoteRequest.SerializeToString,
                response_deserializer=notif__pb2.QuoteResponse.FromString,
                )
        self.GenerateImages = channel.unary_stream(
                '/notif.NotifService/GenerateImages',
                request_serializer=notif__pb2.ImagesRequest.SerializeToString,
                response_deserializer=notif__pb2.ImagesResponse.FromString,
                )


class NotifServiceServicer(object):
    """Define the Notification service
    """

    def GetQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuote': grpc.unary_stream_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=notif__pb2.QuoteRequest.FromString,
                    response_serializer=notif__pb2.QuoteResponse.SerializeToString,
            ),
            'GenerateImages': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateImages,
                    request_deserializer=notif__pb2.ImagesRequest.FromString,
                    response_serializer=notif__pb2.ImagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notif.NotifService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotifService(object):
    """Define the Notification service
    """

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notif.NotifService/GetQuote',
            notif__pb2.QuoteRequest.SerializeToString,
            notif__pb2.QuoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GenerateImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/notif.NotifService/GenerateImages',
            notif__pb2.ImagesRequest.SerializeToString,
            notif__pb2.ImagesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
