# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calc_pb2 as calc__pb2


class CalculatorStub(object):
    """Define the Calculator service with four RPC methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/calc.Calculator/Add',
                request_serializer=calc__pb2.AddRequest.SerializeToString,
                response_deserializer=calc__pb2.AddResponse.FromString,
                )
        self.Subtract = channel.unary_unary(
                '/calc.Calculator/Subtract',
                request_serializer=calc__pb2.SubtractRequest.SerializeToString,
                response_deserializer=calc__pb2.SubtractResponse.FromString,
                )
        self.Multiply = channel.unary_unary(
                '/calc.Calculator/Multiply',
                request_serializer=calc__pb2.MultiplyRequest.SerializeToString,
                response_deserializer=calc__pb2.MultiplyResponse.FromString,
                )
        self.Divide = channel.unary_unary(
                '/calc.Calculator/Divide',
                request_serializer=calc__pb2.DivideRequest.SerializeToString,
                response_deserializer=calc__pb2.DivideResponse.FromString,
                )


class CalculatorServicer(object):
    """Define the Calculator service with four RPC methods
    """

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Multiply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=calc__pb2.AddRequest.FromString,
                    response_serializer=calc__pb2.AddResponse.SerializeToString,
            ),
            'Subtract': grpc.unary_unary_rpc_method_handler(
                    servicer.Subtract,
                    request_deserializer=calc__pb2.SubtractRequest.FromString,
                    response_serializer=calc__pb2.SubtractResponse.SerializeToString,
            ),
            'Multiply': grpc.unary_unary_rpc_method_handler(
                    servicer.Multiply,
                    request_deserializer=calc__pb2.MultiplyRequest.FromString,
                    response_serializer=calc__pb2.MultiplyResponse.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=calc__pb2.DivideRequest.FromString,
                    response_serializer=calc__pb2.DivideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calc.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Define the Calculator service with four RPC methods
    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/Add',
            calc__pb2.AddRequest.SerializeToString,
            calc__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/Subtract',
            calc__pb2.SubtractRequest.SerializeToString,
            calc__pb2.SubtractResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Multiply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/Multiply',
            calc__pb2.MultiplyRequest.SerializeToString,
            calc__pb2.MultiplyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calc.Calculator/Divide',
            calc__pb2.DivideRequest.SerializeToString,
            calc__pb2.DivideResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
