# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calc.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"$\n\nAddRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x18\n\x0b\x41\x64\x64Response\x12\t\n\x01r\x18\x01 \x01(\x05\")\n\x0fSubtractRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1d\n\x10SubtractResponse\x12\t\n\x01r\x18\x01 \x01(\x05\")\n\x0fMultiplyRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1d\n\x10MultiplyResponse\x12\t\n\x01r\x18\x01 \x01(\x05\"\'\n\rDivideRequest\x12\n\n\x02n1\x18\x01 \x01(\x05\x12\n\n\x02n2\x18\x02 \x01(\x05\"\x1b\n\x0e\x44ivideResponse\x12\t\n\x01r\x18\x01 \x01(\x02\x32\xeb\x01\n\nCalculator\x12,\n\x03\x41\x64\x64\x12\x10.calc.AddRequest\x1a\x11.calc.AddResponse\"\x00\x12;\n\x08Subtract\x12\x15.calc.SubtractRequest\x1a\x16.calc.SubtractResponse\"\x00\x12;\n\x08Multiply\x12\x15.calc.MultiplyRequest\x1a\x16.calc.MultiplyResponse\"\x00\x12\x35\n\x06\x44ivide\x12\x13.calc.DivideRequest\x1a\x14.calc.DivideResponse\"\x00\x42\x13Z\x11\x63\x61lculator/calcpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021calculator/calcpb'
  _globals['_ADDREQUEST']._serialized_start=20
  _globals['_ADDREQUEST']._serialized_end=56
  _globals['_ADDRESPONSE']._serialized_start=58
  _globals['_ADDRESPONSE']._serialized_end=82
  _globals['_SUBTRACTREQUEST']._serialized_start=84
  _globals['_SUBTRACTREQUEST']._serialized_end=125
  _globals['_SUBTRACTRESPONSE']._serialized_start=127
  _globals['_SUBTRACTRESPONSE']._serialized_end=156
  _globals['_MULTIPLYREQUEST']._serialized_start=158
  _globals['_MULTIPLYREQUEST']._serialized_end=199
  _globals['_MULTIPLYRESPONSE']._serialized_start=201
  _globals['_MULTIPLYRESPONSE']._serialized_end=230
  _globals['_DIVIDEREQUEST']._serialized_start=232
  _globals['_DIVIDEREQUEST']._serialized_end=271
  _globals['_DIVIDERESPONSE']._serialized_start=273
  _globals['_DIVIDERESPONSE']._serialized_end=300
  _globals['_CALCULATOR']._serialized_start=303
  _globals['_CALCULATOR']._serialized_end=538
# @@protoc_insertion_point(module_scope)
